### ISSUE TITLE
unisat wallet sign messages cannot be verified.

### ISSUE THREAD

**Issue by ygcool** [BitonicNL/verify-signed-message#3]
<img width="330" alt="image" src="https://github.com/BitonicNL/verify-signed-message/assets/16422689/a09ce7b7-5cf5-4d87-a9d1-fd57ce043f96">

Using the P2WPKH/P2SH-P2WPKH/Legacy (P2PKH) formats of the unisat wallet to sign messages cannot be verified.

test website: [https://demo.unisat.io/](https://demo.unisat.io/)

**Comment by ArbitronNL** [comment]
# Legacy

I've tried to sign a message with a [legacy address using Unisat](https://github.com/BitonicNL/verify-signed-message/assets/74659821/cf14a741-f7f0-4c7d-bed7-2326427bd2bd) and it provided an invalid signature on both [Electrum](https://github.com/BitonicNL/verify-signed-message/assets/74659821/e3b20b79-5582-4a86-a1c6-c1da60cea987) and [BrainWalletX](https://github.com/BitonicNL/verify-signed-message/assets/74659821/7a2f6e5d-d7dd-45b2-9118-e236903f7d48). Only [VerifySignedMessage](https://github.com/BitonicNL/verify-signed-message/assets/74659821/a4cccc66-30c3-489d-8eaf-a1b6a75997c2) seems to accept this signature.

After looking at the source code of VerifySignedMessage, I realized that they had a fallback which rebuilds the signature (what the fuck) with different recovery flags and keeps trying to verify the message (actual source code is not public, but it [looks a lot like this](https://github.com/LOCKbusiness/transaction-checker/blob/main/transactionchecker/javascript/app.ts#L39)). This signals to me that UniSat doesn't properly create their signatures, because you should never need to change the actual signature for it to work.

The recovery flag that seems to succeed for UniSat signed message is `31` which means that the address [is actually compressed](https://github.com/btclib-org/btclib/blob/v2022.7.20/btclib/ecc/bms.py#L93). If I compress the address, I do get the proper address back (and the signature is instantly valid). However, the actual signature that UniSat creates gives me the recovery flag `27` which is uncompressed as shown in [the table](https://github.com/btclib-org/btclib/blob/v2022.7.20/btclib/ecc/bms.py#L83) and [the validation code](https://github.com/btclib-org/btclib/blob/v2023.2.3/btclib/ecc/bms.py#L306).

# P2WPKH-P2SH

I've tried to sign a message with a [P2WPKH-P2SH using Unisat](https://github.com/BitonicNL/verify-signed-message/assets/74659821/b4c2ec16-1d21-4add-b3ec-c286fbc0406f) and it provided an invalid signature on [Electrum](https://github.com/BitonicNL/verify-signed-message/assets/74659821/eba93131-ab95-4a68-aa8a-24536456310e). Only [VerifySignedMessage](https://github.com/BitonicNL/verify-signed-message/assets/74659821/ca656617-06b7-4389-8fcb-432e0caf97e3) seems to accept this signature.

For P2WPKH-P2SH UniSat uses recovery flag `28`, which stands for [P2PKH uncompressed](https://github.com/btclib-org/btclib/blob/v2022.7.20/btclib/ecc/bms.py#L83), meaning it will never work in any official implementation. The flag used by VerifyBitcoinMessage was `36`, which would also work with `verify-signed-message` (and provide a valid signed message).

# P2WPKH

I've tried to sign a message with a [P2WPKH using Unisat](https://github.com/BitonicNL/verify-signed-message/assets/74659821/d768a571-ead5-4684-a158-ded660d8fa9b) and it provided an invalid signature on [Electrum](https://github.com/BitonicNL/verify-signed-message/assets/74659821/8922ef2e-4ed9-4adf-be40-b6b2f5daff34). Only [VerifySignedMessage](https://github.com/BitonicNL/verify-signed-message/assets/74659821/188f559a-1d84-4b18-b3f3-fae6f6d6c3fe) seems to accept this signature.

For P2WPKH UniSat uses recovery flag `28`, which stands for [P2PKH uncompressed](https://github.com/btclib-org/btclib/blob/v2022.7.20/btclib/ecc/bms.py#L83), meaning it will never work in any official implementation. The flag used by VerifyBitcoinMessage was `40`, which would also work with `verify-signed-message` (and provide a valid signed message).

---

Since UniSat doesn't create a signature with the recovery flag properly set, it's not adhering to the current standards. Please create an issue with UniSat themselves, as they need to change their code, we will not be adding a non-standard fallback. If it helps, [there already exists an issue for the legacy address](https://github.com/unisat-wallet/extension/issues/11), so it is not an unknown issue.
